version: '3.7'

services:
  dns-server:
    container_name: dns-server
    build: dns-server
    expose:
      - "53/tcp"
      - "53/udp"
  app:
    container_name: app
    command: tail -f /dev/null
    build: app
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - dns-server
    volumes:
      - ./app:/app
